import streamlit as st
import pandas as pd
import plotly.express as px
import sys
import os

print("Current folder:", os.getcwd())
print("Files:", os.listdir("."))
print("Python folder exists:", os.path.exists("Python"))
print("Results folder exists:", os.path.exists("results"))

# Absolute path of project folder
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Path to Python folder
PYTHON_DIR = os.path.join(BASE_DIR, "Python")

# Add Python folder
if PYTHON_DIR not in sys.path:
    sys.path.insert(0, PYTHON_DIR)

from inventory_calculations import InventoryCalculator

# ==========================================
# Page Configuration
# ==========================================

st.set_page_config(
    page_title="Inventory Optimization System",
    page_icon="📦",
    layout="wide"
)

# ==========================================
# Dashboard Title
# ==========================================

st.title("📦 Inventory Optimization System")

st.markdown("---")

st.subheader("Artificial Bee Colony Based Inventory Optimization")

st.write("""
Welcome to the Inventory Optimization Dashboard.

This dashboard displays the optimized inventory
results generated by the Artificial Bee Colony Algorithm.
""")

st.markdown("---")

# ==========================================
# Load Optimization Results
# ==========================================

file_path = "results/optimized_inventory.csv"

if os.path.exists(file_path):

    df = pd.read_csv(file_path)

    st.success("Optimization Results Loaded Successfully ✅")

    st.subheader("📋 Optimized Inventory Results")

    st.dataframe(df, use_container_width=True)

    st.markdown("---")

    st.subheader("📊 Economic Order Quantity (EOQ)")

    fig = px.bar(
        df,
        x="Product",
        y="EOQ",
        color="Product",
        text="EOQ",
        title="EOQ of Products"
    )

    st.plotly_chart(fig, use_container_width=True)

    st.markdown("---")

    st.subheader("💰 Minimum Inventory Cost")

    fig2 = px.bar(
        df,
        x="Product",
        y="Minimum Cost",
        color="Product",
        text="Minimum Cost",
        title="Minimum Inventory Cost"
    )

    st.plotly_chart(fig2, use_container_width=True)

else:

    st.error("optimized_inventory.csv not found!")

st.markdown("---")

# ==========================================
# Two Columns
# ==========================================

left, right = st.columns([1, 2])

# ==========================================
# LEFT PANEL
# ==========================================

with left:

    st.header("📥 Inventory Input")

    product = st.selectbox(
        "Select Product",
        ["Sugar", "Tea", "Coffee", "Laptop", "Rice"]
    )

    annual_demand = st.number_input(
        "Annual Demand",
        min_value=1,
        value=900
    )

    ordering_cost = st.number_input(
        "Ordering Cost",
        min_value=1,
        value=45
    )

    holding_cost = st.number_input(
        "Holding Cost",
        min_value=1,
        value=7
    )

    current_stock = st.number_input(
        "Current Stock",
        min_value=0,
        value=80
    )

    optimize = st.button("🐝 Optimize Inventory")

# ==========================================
# RIGHT PANEL
# ==========================================

with right:

    st.header("📊 Optimization Results")

    if optimize:

        calculator = InventoryCalculator(
            None,
            None,
            None
        )

        eoq = calculator.calculate_eoq(
            annual_demand,
            ordering_cost,
            holding_cost
        )

        st.success("Optimization Completed Successfully ✅")

        col1, col2 = st.columns(2)

        with col1:
            st.metric(
                "Economic Order Quantity (EOQ)",
                f"{eoq:.2f}"
            )

        with col2:
            st.metric(
                "Current Stock",
                current_stock
            )

        if current_stock < eoq:

            st.warning("⚠ Current stock is lower than the recommended EOQ.")

        else:

            st.success("✅ Current stock is sufficient.")

    else:

        st.info("Press '🐝 Optimize Inventory' to calculate EOQ.")

st.markdown("---")

st.caption("Inventory Optimization System | MPhil Project")
